# Generated by Django 6.0.3 on 2026-04-12 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('food_name', models.CharField(db_index=True, max_length=255)),
                ('analysis_type', models.CharField(choices=[('text', 'Text Analysis'), ('image', 'Image Analysis'), ('cooking', 'Cooking Recipe')], max_length=20)),
                ('profile_hash', models.CharField(default='', max_length=16)),
                ('response_json', models.TextField()),
                ('hit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['food_name', 'analysis_type'], name='fitness_ana_food_na_0e3977_idx'), models.Index(fields=['created_at'], name='fitness_ana_created_23d602_idx')],
            },
        ),
    ]
