# Generated by Django 6.0.3 on 2026-04-12 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('WEIGHT_LOSS', 'Giảm cân'), ('WEIGHT_GAIN', 'Tăng cân'), ('MUSCLE_GAIN', 'Tăng cơ'), ('MAINTAIN', 'Duy trì cân nặng'), ('CUSTOM', 'Tùy chỉnh')], max_length=20)),
                ('target_calories', models.IntegerField(blank=True, null=True)),
                ('target_protein', models.FloatField(blank=True, help_text='grams per day', null=True)),
                ('target_carbs', models.FloatField(blank=True, help_text='grams per day', null=True)),
                ('target_fat', models.FloatField(blank=True, help_text='grams per day', null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='fitness_use_user_id_432dd6_idx')],
            },
        ),
    ]
