# Generated by Django 6.0.3 on 2026-04-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerprofile',
            name='age',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='consumerprofile',
            name='height',
            field=models.FloatField(default=170.0),
        ),
        migrations.AlterField(
            model_name='consumerprofile',
            name='weight',
            field=models.FloatField(default=70.0),
        ),
    ]
