# Generated by Django 6.0.3 on 2026-04-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('general', 'Chung'), ('study', 'Học tập'), ('love', 'Tình yêu'), ('sales', 'Bán hàng')], default='general', max_length=50),
        ),
    ]
